# Generated by CMake, DO NOT EDIT
/Users/christoph/Documents/Projects/Zelda/build_mac/CMakeFiles/cmake.check_cache: \
/Users/christoph/Documents/Projects/Zelda/ResourcesJar/Buttons/buttons_keyboard.imageset\
/Users/christoph/Documents/Projects/Zelda/ResourcesJar/Buttons/buttons_keyboard.png\
/Users/christoph/Documents/Projects/Zelda/Zelda/CMakeLists.txt\
/Users/christoph/Documents/Projects/Zelda/cmake/templates/GlobalBuildDefines.hpp.in\
/Users/christoph/Documents/Projects/Zelda/cmake/templates/plugins.cfg.in\
/Users/christoph/Documents/Projects/Zelda/cmake/templates/resources.cfg.in\
/Users/christoph/Documents/Projects/Zelda/cmake/toolchain/CopyButtonImageset.cmake\
/Users/christoph/Documents/Projects/Zelda/cmake/toolchain/CopyResources.cmake\
/Users/christoph/Documents/Projects/Zelda/cmake/toolchain/CreateGlobalDefines.cmake
	/opt/local/bin/cmake -H/Users/christoph/Documents/Projects/Zelda -B/Users/christoph/Documents/Projects/Zelda/build_mac
